### ISSUE TITLE
bug found in Utils/PrintFilesInDirectory.js

### ISSUE THREAD

**Issue by pas-by** [Cyclone3DR/Scripts#3]
the output variable 'fileName' has a 'line feed' char. at the end of the string.
you guys should add a snippet somewhat like the following:

//  the program insert a 'line feed' char. at the end of string.
//  btw, my 3dr doesn't support fileName.endsWith() function
if (fileName.charAt(fileName.length-1)=='\n')
    fileName = fileName.substring(0, fileName.length-1);

**Comment by Technodigit** [comment]
Hello @pas-by, thanks for reporting this behavior.
It will be fixed in the future major release. Check for the reference RSHP-33398 in the release note.
