### ISSUE TITLE
Can you provide some examples of using ScanToMesh?

### ISSUE THREAD

**Issue by IhorKram** [Cyclone3DR/Scripts#4]
I have noticed, that mesh that I created manually inside the app is much better than the one which I created by code (using the ScanToMesh function). I think that I did something wrong. It would be good to have some examples, to see what I did wrong.
Can you please provide some examples of how to use ScanToMesh?

**Comment by Technodigit** [comment]
Hello @IhorKram ,

You have two possibilities when calling `ScanToMesh` algorithm in script.

1. Create a mesh by specifying the type of scanner (same as Default settings):
```js
var myCloud = SCloud.All(1)[0];
var res = SPoly.ScanToMesh(
   myCloud,
   SPoly.BLK360,
   true,
   false);

if(res.ErrorCode == 0)
{
   res.Poly.AddToDoc();
   res.Poly.SetPolyRepresentation(SPoly.POLY_TEXTURE);
}
```

2. Create a mesh by specifying each parameter (same as Advanced settings):
```js
var myCloud = SCloud.All(1)[0];
var res = SPoly.ScanToMesh(
    myCloud,
    25,
    0.05,
    0.2,
    0.01,
    true);

if(res.ErrorCode == 0)
{
   res.Poly.AddToDoc();
   res.Poly.SetPolyRepresentation(SPoly.POLY_TEXTURE);
}
```

Hope it helps.

**Comment by Gaztwin86** [comment]
Hey

Want to write a script to extract surface features

Like paths, curb , linemarking, fences , building footprints , trees , poles
Etc

Can anyone help ?













________________________________

**Comment by Gaztwin86** [comment]
Hello

I have started one

I think
Sorry I’m new to this









Kind Regards



Garry Elali

Operations Manager

[Image]

1a/10 Exchange Parade, Smeaton Grange, 2567

0403 144 986

***@***.******@***.***>

geotwin.com.au  <https://geotwin.com.au/>



[Linkedin icon - Free download on Iconfinder]<https://www.linkedin.com/company/geotwinspatial/mycompany/?viewAsMember=true>     [Image] <https://www.instagram.com/geotwin_/>      [Image] <https://www.youtube.com/channel/UCopJyCLIOSqbcJfeE37jByg/featured>

This email, and any files transmitted with it, are confidential and intended for use by the addressee only. The confidential nature of the information contained in the email and/or file attachment is not waived, lost or destroyed if it is sent to other than the addressee. Use or dissemination of the information contained in the email and/or file attachment, by a recipient other than the addressee, may cause commercial damage to both/either the sender and/or addressee. If you are not the addressee of this email/file attachment contact the sender immediately and delete this email/file attachment.

P Please consider the environment before printing this email.



________________________________
