### ISSUE TITLE
Extraction

### ISSUE THREAD

**Issue by Gaztwin86** [Cyclone3DR/Scripts#5]
Looking to how to extract underside of bridge

**Comment by Technodigit** [comment]
Hello @Gaztwin86,

You can take a look at the favorite scripts **"Electric Line Extraction"** and **"Curb Extraction"** that are embedded in C3DR to give you example on how to extract lines from seed points.
Additionally, the functions `SCloud.ExtractMultilineFromSeed` and `SCloud.RegionGrowFreePolyline` may be worth the try.

Be aware that the script will strongly depend on your data.
Therefore, I'd suggest contacting your local support to help you further in designing your script.

**Comment by Gaztwin86** [comment]
Hey !

would these work for lane lines, fences and paths?? (To extract them )

**Comment by Gaztwin86** [comment]
Hello,

Where do I find these scripts

Kind Regards

Garry Elali
Operations Manager
***@***.***
1a/10 Exchange Parade, Smeaton Grange, 2567
0403 144 986
***@***.******@***.***>
geotwin.com.au  <https://geotwin.com.au/>

[Linkedin icon - Free download on Iconfinder]<https://www.linkedin.com/company/geotwinspatial/mycompany/?viewAsMember=true>     ***@***.*** <https://www.instagram.com/geotwin_/>      ***@***.*** <https://www.youtube.com/channel/UCopJyCLIOSqbcJfeE37jByg/featured>
This email, and any files transmitted with it, are confidential and intended for use by the addressee only. The confidential nature of the information contained in the email and/or file attachment is not waived, lost or destroyed if it is sent to other than the addressee. Use or dissemination of the information contained in the email and/or file attachment, by a recipient other than the addressee, may cause commercial damage to both/either the sender and/or addressee. If you are not the addressee of this email/file attachment contact the sender immediately and delete this email/file attachment.
P Please consider the environment before printing this email.
